// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/detalles/:id": {
    params: {
      "id": string;
    };
  };
  "/tendencias": {
    params: {};
  };
  "/contacto": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/detalles/:id" | "/tendencias" | "/contacto";
  };
  "./routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/detalles.$id.jsx": {
    id: "routes/detalles.$id";
    page: "/detalles/:id";
  };
  "./routes/tendencias.jsx": {
    id: "routes/tendencias";
    page: "/tendencias";
  };
  "./routes/contacto.jsx": {
    id: "routes/contacto";
    page: "/contacto";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.jsx");
  "routes/home": typeof import("./src/app/./routes/home.jsx");
  "routes/detalles.$id": typeof import("./src/app/./routes/detalles.$id.jsx");
  "routes/tendencias": typeof import("./src/app/./routes/tendencias.jsx");
  "routes/contacto": typeof import("./src/app/./routes/contacto.jsx");
};